import code as x 
x.create("suji",25)
x.create("src",70,3600) 
x.read("suji")
x.read("src")
x.create("suji",50)
x.modify("suji",55)
x.delete("suji")
t1=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t1.start()
t1.sleep()
t2=Thread(target=(create or read or delete),args=(key_name,value,timeout))
t2.start()
t2.sleep()
